import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { checkout } from "../checkout"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>🚀Cyberguard🚀</h1>
        <div className={styles.grid}>
          <div>
            <Image
              src="/images/Stick1.jpg"
              alt="NFT"
              width={400}
              height={400}
            />
            {/* <p>Very expensive art piece 1</p> */}
            <br />
            <button onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1O4JeDSAAbl28UHdquw7wH1w",
                    quantity: 1
                  }
                ]
              })
            })}>Donate!</button>
          </div>
          {/* <div>
            <Image
              src="/images/Stick2.jpg"
              alt="NFT"
              width={400}
              height={400}
            />
            <p>Very expensive art piece 2</p>
          </div> */}
        </div>
      </main>
    </div>
  )
}
